"""fix model import and update tables

Revision ID: c08c46841348
Revises: 1cbc46805e81
Create Date: 2025-11-07 17:06:39.393844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08c46841348'
down_revision: Union[str, Sequence[str], None] = '1cbc46805e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='持仓日期'),
    sa.Column('security_code', sa.Integer(), nullable=False, comment='证券代码'),
    sa.Column('security_name', sa.String(length=100), nullable=False, comment='证券名称'),
    sa.Column('holding_amount', sa.Float(), nullable=False, comment='持仓数量'),
    sa.Column('available_amount', sa.Integer(), nullable=False, comment='可用数量'),
    sa.Column('cost_price', sa.Float(), nullable=False, comment='持仓成本价'),
    sa.Column('latest_price', sa.Float(), nullable=False, comment='最新价'),
    sa.Column('holding_profit_ratio', sa.Float(), nullable=True, comment='持仓盈亏比例（%）'),
    sa.Column('holding_profit', sa.Float(), nullable=True, comment='持仓盈亏金额'),
    sa.Column('daily_profit_ratio', sa.Float(), nullable=True, comment='当日盈亏比例（%）'),
    sa.Column('daily_profit', sa.Float(), nullable=True, comment='当日盈亏金额'),
    sa.Column('avg_buy_price', sa.Float(), nullable=True, comment='买入均价'),
    sa.Column('position_ratio', sa.Float(), nullable=True, comment='个股仓位（%）'),
    sa.Column('latest_value', sa.Float(), nullable=True, comment='最新市值'),
    sa.Column('market', sa.String(length=50), nullable=True, comment='交易市场'),
    sa.Column('shareholder_account', sa.String(length=50), nullable=True, comment='股东账号'),
    sa.Column('currency', sa.String(length=20), nullable=True, comment='币种'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_record_date'), 'holding_record', ['date'], unique=False)
    op.create_index(op.f('ix_holding_record_id'), 'holding_record', ['id'], unique=False)
    op.create_index(op.f('ix_holding_record_security_code'), 'holding_record', ['security_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holding_record_security_code'), table_name='holding_record')
    op.drop_index(op.f('ix_holding_record_id'), table_name='holding_record')
    op.drop_index(op.f('ix_holding_record_date'), table_name='holding_record')
    op.drop_table('holding_record')
    # ### end Alembic commands ###
